#!/bin/sh

. /lib/netifd/netifd-proto.sh

interface="$TLSVPN_NETIFD_INTERFACE"
device="$TLSVPN_DEVICE"

[ -n "$interface" ] && [ -n "$device" ] || exit 1

proto_init_update "$device" 0
proto_send_update "$interface"
